# Generated by Django 5.0.7 on 2024-07-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_rename_doctors_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
